name: Update Design Tokens

on:
  push:
    branches:
      - main
    paths:
      - "design-tokens/**/*.json"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: update-design-tokens
  cancel-in-progress: true

jobs:
  build-and-pr:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build style dictionary outputs
        run: npm run build:tokens

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "style: update design tokens from Figma"
          title: "Update Design Tokens"
          body: "This PR was automatically generated by Style Dictionary based on the latest Figma token update. Please check the impact on the code manually and merge"
          branch: "design-token-updates"
          base: "main"
          delete-branch: true
          add-paths: |
            style-dictionary/**
